### ISSUE TITLE
域名似乎已经变成菠菜了？

### ISSUE THREAD

**Issue by asjdf** [fuyiqing/fuyiqing.github.io#1]
很高兴看到您的博客，但是似乎出现了一些域名上的问题？

**Comment by fuyiqing** [comment]
😂谢谢你访问我的博客，我是之前有一个fuyiqing.net，但是没有续费服务器和域名，所以博客就被释放了，不好意思让你失望了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月24日(周五) 晚上7:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [fuyiqing/fuyiqing.github.io] 域名似乎已经变成菠菜了？ (Issue #1)




 
很高兴看到您的博客，但是似乎出现了一些域名上的问题？
